### ISSUE TITLE
Paths MUST be relative to repository root

### ISSUE THREAD

**Issue by xeruf** [alerque/git-warp-time#4]
Paths must be relative to repository root and the script needs to be run in the repository root.

This tripped me off, as neither relative paths in a subdirectory nor absolute paths worked - but the output was silent whether it worked or not...

Should be added to the manpage and an error message added

**Comment by alerque** [comment]
Good point. I use almost all tools (not just this) at repository roots so I didn't bump into this, but I'd be happy to fix it.

What would be the most expected input though? Make it *always* relative to PWD? Or with some special syntax for repository root? Most Git tools I can think of use PWD relative paths so maybe that should just be the default.

**Comment by alerque** [comment]
And yes also an error for non-existing or non-tracked paths would be good...

**Comment by alerque** [comment]
I just worked up a change that makes *all* path inputs be assumed to be relative to the `$PWD` and converts them to paths relative to the repository use only for internal use. Does making that the default behaviour sound correct to you?

**Comment by xeruf** [comment]
yes sounds good :)

**Comment by alerque** [comment]
Released as v0.5.0.
